name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Code uthao (checkout)
        uses: actions/checkout@v4

      - name: Node install karo
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Dependencies install karo
        run: npm install

      - name: Build check
        run: npm run build

      - name: Test check
        run: npm test
